# Exercise
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression
SVM
Decision Tree
Random Forest

In [3]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np


In [2]:
iris= load_iris()

In [6]:
#Logistic Regeression
L_scores = cross_val_score(LogisticRegression(),iris.data,iris.target)
L_scores

C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
np.average(L_scores)

0.9733333333333334

In [9]:
#Decision Tree

d_score =  cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [10]:
np.average(d_score)

0.9533333333333334

In [11]:
#SVM

s_score = cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [13]:
np.average(s_score)

0.9666666666666666

In [15]:
#random forest

r_score = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
r_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [16]:
np.average(r_score)

0.9666666666666668

In [ ]:
Best score so far is from SVM: 0.9666666666666666