# KFold Cross Validation 

In [3]:
from sklearn.datasets import load_digits
digits=load_digits()

In [6]:
print (digits['DESCR'])

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(digits.data, digits.target, test_size=0.3)

# Logistic regression

In [10]:
lr=LogisticRegression()
lr.fit( X_train,y_train)
lr.score(X_test,y_test)

C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [11]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9481481481481482

# SVM

In [24]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.9833333333333333

In [18]:
svm1= SVC(gamma='auto')
svm1.fit(X_train, y_train)
svm1.score(X_test, y_test)

0.3685185185185185

#    # Random Foest

In [14]:
rf= RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test, y_test)

0.975925925925926

In [19]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test, y_test)

0.9722222222222222

# KFold cross validation
Basic example

In [20]:
from sklearn.model_selection import KFold

In [21]:
kf=KFold(n_splits=3)

In [22]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Use KFold for our digits example

In [39]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    
    return model.score(X_test,y_test)

In [40]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

scores_logistic=[]
scores_svm=[]
score_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    
    scores_logistic.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

In [41]:
scores_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [42]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [43]:
score_rf

[0.9398998330550918, 0.9632721202003339, 0.9265442404006677]

In [44]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [47]:
scores_logistic1 = []
scores_svm1 = []
scores_rf1 = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic1.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm1.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf1.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [48]:
scores_logistic1

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [49]:
scores_svm1

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [51]:
scores_rf1

[0.9248747913188647, 0.9499165275459098, 0.9382303839732888]

# cross_val_score function

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [55]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

svm model performance using cross_val_score

In [56]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [57]:
#random forest performance using cross_val_score

cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)


array([0.92320534, 0.95993322, 0.91318865])