# Machine Learning With Python: Save And Load Trained Model


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model =linear_model.LinearRegression()

In [4]:
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

array([859554.79452055])

# Save Model To a File Using Python Pickle


In [8]:
import pickle

In [9]:
with open ('model_pickle','wb') as file: #write binary
    pickle.dump(model,file)

# Load Saved Model


In [10]:
with open('model_pickle','rb') as file: #read binary
    np=pickle.load(file)

In [11]:
np.coef_

array([135.78767123])

In [12]:
np.intercept_

180616.43835616432

In [13]:
np.predict([[4000]])

array([723767.12328767])

# Save Trained Model Using joblib


In [17]:
pip install joblib

In [23]:
import joblib

In [25]:
joblib.dump(model, 'model_joblib')


['model_joblib']

# Load Saved Model


In [26]:
mj = joblib.load('model_joblib')


In [27]:
mj.coef_

array([135.78767123])

In [28]:
mj.predict([[7553]])

array([1206220.71917808])