In [1]:
import numpy as np
import time
import sys

In [8]:
l1=range(1000)
print(l1)
l1[12]
#print size of list
print(sys.getsizeof(5))
print(sys.getsizeof(5)*len(l1))

range(0, 1000)
28
28000


In [2]:
arr=np.arange(1000)
print(arr.size)
print(arr.itemsize)
print(arr.size*arr.itemsize)

1000
4
4000


#numpy is fater than python list

In [6]:
size=1000

l1=range(1000)
l2=range(1000)

a1=np.arange(size)
a2=np.arange(size)

#python list

start= time.time()
result=[(x+y) for x,y in zip (l1,l2)]
print('python list look ',(time.time()-start)*1000)

#nump arry

start= time.time()
result=[(x,y) for x,y in zip(a1,a2)]
print('numpy arry took',(time.time()-start)*1000)




python list look  1.0008811950683594
numpy arry took 1.0008811950683594


In [7]:
a=np.array([1,2,3,4,5])
a[0]

1

In [8]:
#to know dimension
a=np.array([[1,2,3],[4,5,5],[6,7,8]])
print(a.ndim)


2


In [9]:
a=np.array([[[1,2,3],[4,5,5],[6,7,8]]])
print(a.ndim)


3


In [10]:
#itme size of int in byte
a=np.array([[[1,2,3],[4,5,5],[6,7,8]]])
print(a.itemsize)
a.dtype

4


dtype('int32')

In [11]:
#itme size of float
a=np.array([[[1.0,2.1,3.2],[4.20,5.25,5.25],[6.25,725,8.25]]])
print(a.itemsize)
a.dtype

8


dtype('float64')

In [48]:
#another way for initilizing with diffrent data type
a=np.array([[[1,2,3],[4,5,5],[6,7,8]]],dtype='float64')
a.dtype

dtype('float64')

In [49]:
a

array([[[1., 2., 3.],
        [4., 5., 5.],
        [6., 7., 8.]]])

In [50]:
a.size

9

In [58]:
#complex no
a=np.array([[1,2,3,4],[4,5,6,6],[7,8,9,23]],dtype=complex)
a


array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j, 23.+0.j]])

In [46]:
#itme size of string
a=np.array([[['aaa','bbb','ccc'],['dota','pubg','2dots'],['hp','lenovo','apple']]])
print(a.itemsize)
a.dtype

24


dtype('<U6')

In [59]:
#initalizing with zero

a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
#we have range() function in pyton, numpy has similar fuction to that arange()

l=range(10)

print(l[0])
print(l[1])
print(l[8])

l1=range(0,2)
print(l1[0])
print(l1[1])

0
1
8
0
1


In [76]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [78]:
#steps of 2 nos
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [82]:
#to generate linearly spaced no , using function linspace(start,stop,no of vari you want)
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [83]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a,'\nThe array size for above array is ')
a.shape


[[1 2 3 4]
 [5 6 7 8]] 
The array size for above array is 


(2, 4)

In [14]:
a.max()

8

In [15]:
a.min()

1

In [17]:
#axis=0 represent row wise
a.sum(axis=0)

array([ 6,  8, 10, 12])

In [18]:
#axis=1 represt column wise
a.sum(axis=1)

array([10, 26])

In [100]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [101]:
np.std(a)

2.29128784747792

In [114]:
a=np.array([[1,2,3],[1,2,4]])
a

array([[1, 2, 3],
       [1, 2, 4]])

In [115]:
b=np.array([[3,2,3],[4,2,1]])
b

array([[3, 2, 3],
       [4, 2, 1]])

In [116]:
a+b

array([[4, 4, 6],
       [5, 4, 5]])

In [117]:
a*b

array([[3, 4, 9],
       [4, 4, 4]])

In [118]:
a/b

array([[0.33333333, 1.        , 1.        ],
       [0.25      , 1.        , 4.        ]])

In [126]:
#slicing in python
n=[1,2,3]
n[0:2]

[1, 2]

In [127]:
n[-1]

3

In [128]:
#slicing in numpy
a=np.array([1,2,3,4,5])

In [129]:
a[0:4]

array([1, 2, 3, 4])

In [131]:
a[-4:-1]

array([2, 3, 4])

In [132]:
a=np.array([[1,2,3,4],[4,5,6,6],[7,8,9,23]],dtype=int)
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  6],
       [ 7,  8,  9, 23]])

In [133]:
a[1,0]

4

In [134]:
a[1:,0:2]

array([[4, 5],
       [7, 8]])

In [139]:
a=np.array([[1,2,3,4],[4,5,6,6],[7,8,9,23]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  6],
       [ 7,  8,  9, 23]])

In [142]:
for row in a:
    print(a)

[[ 1  2  3  4]
 [ 4  5  6  6]
 [ 7  8  9 23]]
[[ 1  2  3  4]
 [ 4  5  6  6]
 [ 7  8  9 23]]
[[ 1  2  3  4]
 [ 4  5  6  6]
 [ 7  8  9 23]]


In [145]:
#flating in 1 D
for cell in a.flat:
    print(cell)

1
2
3
4
4
5
6
6
7
8
9
23


In [23]:
#stacking array
a=np.arange(15).reshape(3,5)
b=np.arange(15).reshape(3,5)

In [24]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [154]:
 np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
z=np.arange(30).reshape(2,15)
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [166]:
#spliting horizonaly
np.hsplit(z,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [167]:
np.vsplit(z,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [183]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
b= a>5
b


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [186]:
#print true value
a[b]


array([ 6,  7,  8,  9, 10, 11])

In [180]:
#replce false value with certain no

a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

# iterate numpy array using nditer 

In [31]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [34]:
for row in a:
    for cell in (row):
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [35]:
#use of flatten()

for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [36]:
#c order means row wise

for row in np.nditer(a,order='c'):
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [37]:
#F order(forten order) means column wise

for row in np.nditer(a,order='f'):
    print(row)

0
4
8
1
5
9
2
6
10
3
7
11


In [38]:
#print value vertically indivially

for row in np.nditer(a,order='F',flags=['external_loop']):
    print(row)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [40]:
#for editing the array
#Modify array values while iterating

for row in  np.nditer(a,op_flags=['readwrite']):
    row[...]=row*row
a



array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# Iterate two broadcastable arrays concurrently


In [41]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [224]:
for (x,y) in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
