# prepare data
Sample problem of predicting home price in monroe, new jersey (USA)
Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.

In [24]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [25]:
url='https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv'

In [27]:
df=pd.read_csv(url)

In [28]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# Data Preprocessing: Fill NA values with median value of a column



In [29]:
df['bedrooms'].median()

4.0

In [31]:
#median is coming like 3.5 then we covert in int so,
import math
median_bebroom=math.floor(df.bedrooms.median())
median_bebroom

4

In [32]:
df.bedrooms= df.bedrooms.fillna(df.bedrooms.median())

In [33]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [34]:
reg =linear_model.LinearRegression()

In [36]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [37]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [38]:
reg.intercept_

221323.00186540408

In [45]:
#Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

reg.predict([[3000,3,40]])

array([498408.25158031])

In [41]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.00186540408

498408.2515740241

In [42]:
reg.predict([[2500,3,4]])

array([558718.87532003])

In [46]:
#Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

reg.predict([[2500,4,3]])

array([585339.4733066])

# Exercise
In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [49]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5586 sha256=085b4ad40a89f6ceaa650fad19b9a6b35f58cf1f9dba3171c82a209b9a742775
  Stored in directory: c:\users\piyush\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number



In [70]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [79]:
url='https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv'
df=pd.read_csv(url)

In [80]:
df.to_csv('hiring.csv',index=False)

In [81]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [83]:
df.experience=df.experience.fillna('zero')

In [84]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [85]:
df.experience=df.experience.apply(w2n.word_to_num)

In [69]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [89]:
import math
median_testscore= df['test_score(out of 10)'].median()
median_testscore


8.0

In [90]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_testscore)

In [91]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [102]:
reg=linear_model.LinearRegression()

In [103]:
reg

LinearRegression()

In [104]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [108]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [109]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [106]:
reg.predict([[9,9,9]])

array([79512.37263464])